stages:
  - build
  - test

image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u heronsousa

frontend-build:
  stage: build
  before_script:
    - echo "Building frontend..."
  script:
    - docker build -f ./frontend/Dockerfile -t heronsousa/workshop-ci-entrega-02_frontend:build ./frontend
    - docker push heronsousa/workshop-ci-entrega-02_frontend:build
  after_script:
    - echo "Successfully built frontend"

backend-build:
  stage: build
  before_script:
    - echo "Building backend..."
  script:
    - docker build -f ./backend/Dockerfile -t heronsousa/workshop-ci-entrega-02_backend:build ./backend
    - docker push heronsousa/workshop-ci-entrega-02_backend:build
  after_script:
    - echo "Successfully built backend"

frontend-test:
  image: docker/compose:latest
  stage: test
  before_script:
    - echo "Testing frontend..."
  script:
    - docker-compose run --entrypoint "npm run test" frontend
  after_script:
    - echo "Successfully tested frontend"

backend-test:
  stage: test
  before_script:
    - echo "Testing backend..."
  script:
    - echo "Run test"
  after_script:
    - echo "Successfully tested backend"
