stages:
  - build
  - test

image: docker:latest

services:
  - docker:dind

frontend-build:
  stage: build
  before_script:
    - echo "Building frontend..."
  script:
    - echo "Run build"
  after_script:
    - echo "Successfully built frontend"

backend-build:
  stage: build
  before_script:
    - echo "Building backend..."
  script:
    - echo "Run build"
  after_script:
    - echo "Successfully built backend"

frontend-test:
  stage: test
  before_script:
    - echo "Testing frontend..."
  script:
    - echo "Run test"
  after_script:
    - echo "Successfully tested frontend"

backend-test:
  stage: test
  before_script:
    - echo "Testing backend..."
  script:
    - echo "Run test"
  after_script:
    - echo "Successfully tested backend"
